//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Address.Formatter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class AddressFormatSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AddressFormatSettings defaultInstance = ((AddressFormatSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AddressFormatSettings())));
        
        public static AddressFormatSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<Address.Formatter.AddressFormat> Formats {
            get {
                return ((global::System.Collections.Generic.List<Address.Formatter.AddressFormat>)(this["Formats"]));
            }
        }
    }
}
